import type { IComponentStyles } from './types';

export const componentStyles: IComponentStyles = {
    ActivityIndicator: {},
    Button: {},
    Image: {},
    Switch: {},
    TextInput: {},
    H1: {},
    H2: {},
    H3: {},
    H4: {},
    H5: {},
    H6: {},
    Heading: {},
    Italic: {},
    Label: {},
    Strikethrough: {},
    Strong: {},
    Text: {},
    Underline: {},
    View: {},
};

export const {
    ActivityIndicator,
    Button,
    Image,
    Switch,
    Text,
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    Heading,
    Italic,
    Label,
    Strikethrough,
    Strong,
    TextInput,
    Underline,
    View,
} = componentStyles;
